### ISSUE TITLE
Reading parquet data from S3

### ISSUE THREAD

**Issue by niklasvm** [rstudio/sparklyr#432]
Good day

The *spark_read_parquet* documentation references that data can be read in from S3. When I attempt to read in a file given an S3 path I get the error: **org.apache.spark.sql.AnalysisException: Path does not exist**. When I debug this error I notice that the code calls **spark_normalize_path** which appends the current working directory to the path.

For example if I call
```{R}
spark_read_parquet(sc, 'parquet_table', 's3n://mybucket/my file.parquet')
```
the **spark_normalize_path** function converts the S3 path to 'file://C:/Data/s3n://mybucket/my file.parquet' which then results in an error.

Are you able to assist?

**Comment by javierluraschi** [comment]
Hi @niklasvm, this seems to be a problem in `sparklyr` under some operating systems, mostly scoped to Windows. I've pushed a fi that you can use after installing `sparklyr` from github as:

```
devtools::install_github("rstudio/sparklyr")
```

**Comment by kevinushey** [comment]
What about using `normalizePath(..., winslash = "/")` here? (Is the problem that `/` are converted to `\`?)

**Comment by niklasvm** [comment]
Hi there. Thanks for the response. It still doesn't read successfully. I notice that in your update:

```{r}
spark_normalize_path <- function(path) {
  # only normalize paths in OS that behave correctly for custom
  # protocols, in windows, this is not the case. See #432
  if (normalizePath("s3n://", mustWork = FALSE) == "s3n://") {
    normalizePath(path, mustWork = FALSE)
  }
}
```
Nothing is returned if the if statement returns false. Could this be the new issue?
