### ISSUE TITLE
please consider re-opening spark 2.1 R code execution error #473

### ISSUE THREAD

**Issue by andrekos2** [rstudio/sparklyr#657]
please consider re-opening spark 2.1 R code execution error #473 - exactly the same problem with sparklyr 0.5.4 using RStudio Server - see next comment for an example

> library(sparklyr)
> sc <- spark_connect(master = "local")
> iris_tb<-copy_to(sc,iris)
Error: Variables must be length 1 or 1.
Problem variables: 'database'
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.1 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sparklyr_0.5.4

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10     withr_1.0.2      digest_0.6.12    dplyr_0.5.0      rprojroot_1.2    assertthat_0.2.0 rappdirs_0.3.1   R6_2.2.0        
 [9] jsonlite_1.4     DBI_0.6-1        backports_1.0.5  magrittr_1.5     httr_1.2.1       devtools_1.12.0  config_0.2       tools_3.4.0     
[17] parallel_3.4.0   yaml_2.1.14      compiler_3.4.0   base64enc_0.1-3  memoise_1.1.0    tibble_1.3.0

**Comment by andrekos2** [comment]
if I execute the code below as a block (all lines at once) - no error and seems a suitable workaround for me
if I comment out the iris_tb line  - error 
if I execute line by line - error

    sc <- spark_connect(master = "local")
    iris_tb<-copy_to(sc,iris)
    x<-spark_read_csv(sc, "gludat", "sync/gludat.csv",header = TRUE, delimiter = ",")
    spark_write_parquet(x, "sync/gludat_parquet",mode='overwrite')

![image](https://cloud.githubusercontent.com/assets/26861595/25652097/0af310ec-3019-11e7-8009-02ece8930d39.png)

**Comment by javierluraschi** [comment]
@andrekos2 would installing the development version of `sparklyr` solve this issue? YOu can install with: `devtools::install_github("rstudio/sparklyr")`, the next major release to CRAN will contain this fix.

**Comment by charleswg** [comment]
Got the same error messages over two Windows PC. (after Rstudio crashed). I resolved it doing those in R (not Rstudio). Rstudio Spark panel, although not connected, seems loading many packages (dplyr, dbplyr) by default:
devtools::install_github("tinyverse/dplyr")
devtools::install_github("rstudio/sparklyr")

**Comment by kevinushey** [comment]
This issue should be fixed either by reinstalling dplyr + sparklyr from CRAN or the development versions together, e.g.

```
install.packages(c("dplyr", "sparklyr"))
```

or

```
devtools::install_github("hadley/dplyr")
devtools::install_github("rstudio/sparklyr")
```

Make sure you execute these in a clean R session and restart after doing this.

**Comment by 3zhang** [comment]
@kevinushey I followed your steps to reinstall dplyr and sparklyr but the problem is still there. The error is only generated when I am using RStudio.

**Comment by andrekos2** [comment]
@3zhang it did fix my problem, though  - with RStudio Server

**Comment by 3zhang** [comment]
Which one did you install? From github or from R cran?

**Comment by andrekos2** [comment]
I now can't remember - try both - perhaps start from the github one.

**Comment by charleswg** [comment]
If you are using Rstudio desktop, please follow my previous comments and fix it in R. 

Best,
Kelvin

**Comment by 3zhang** [comment]
OK. I could not install the latest dplyr due to some strange error (I already wrote an issue to dplyr project). So I directly edited the source code (sdf_collect) in my sparklyr package based on the latest version, repackaged all the files and installed. It works.
